[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
programs = "3HBzNutk8DrRfffCS74S55adJAjgY8NHrWXgRtABaSbF"

[programs.devnet]
programs = "3HBzNutk8DrRfffCS74S55adJAjgY8NHrWXgRtABaSbF"

[programs.mainnet]
programs = "3HBzNutk8DrRfffCS74S55adJAjgY8NHrWXgRtABaSbF"

[registry]
url = "https://api.apr.dev"

[provider]

cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/main.test.ts"
