name: Anchor Tests

on:
  push:
    branches: [ '**' ]
#  pull_request:
#    branches: [ '**' ]

jobs:
  test:
    name: Run Anchor Tests in Docker
    runs-on: ubuntu-latest
    
    container:
      image: pylejeune/solana-dev:beta
      # Ne pas utiliser --user root sauf si absolument nécessaire
      # car cela peut modifier l'environnement attendu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify container environment
        shell: bash
        run: |
          echo "=== Current user ==="
          id
          echo "=== Working directory ==="
          pwd
          ls -la
          echo "=== Environment variables ==="
          env | sort
          echo "=== Installed tools ==="
          which anchor solana cargo
          echo "=== Versions ==="
          anchor --version || true
          solana --version || true

      - name: Generate Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase --force --outfile ~/.config/solana/id.json

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        working-directory: front
        run: |
          yarn install --frozen-lockfile

      - name: Install ts-mocha on programs
        working-directory: programs
        run: |
          yarn add ts-mocha@10.0.0 @types/mocha chai @types/chai

#      - name: Start Solana test validator
#        run: solana-test-validator &
        
#      - name: Wait for validator to start
#        run: sleep 5

      # Cache pour la compilation Anchor
      - name: Cache Anchor build
        uses: actions/cache@v3
        with:
          path: |
            programs/target
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-anchor-${{ hashFiles('programs/Cargo.lock', 'programs/Cargo.toml', 'programs/programs/**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-anchor-

      - name: Build Anchor program
        working-directory: programs
        run: |
          anchor build

      - name: Run Anchor tests
        shell: bash
        working-directory: programs
        run: |
          anchor test --skip-build