name: Tests E2E et Couverture de Code

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    name: Tests E2E et rapport de couverture
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4

      - name: Installation de netcat
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd
        working-directory: .

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation de pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Configuration du cache pnpm
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Installation des dépendances
        run: pnpm install --no-frozen-lockfile

      - name: Installation de Playwright
        run: npx playwright install --with-deps

      - name: Build de l'application Next.js
        run: pnpm run build

      - name: Lancement du serveur Next.js
        run: pnpm run start &
        env:
          NODE_ENV: test
          PORT: 3000

      - name: Attente du démarrage du serveur
        run: |
          echo "Attente du démarrage du serveur..."
          while ! nc -z localhost 3000; do
            sleep 1
          done
          echo "Serveur démarré!"

      - name: Exécution des tests E2E
        run: pnpm run test:e2e
        env:
          BASE_URL: http://localhost:3000

      - name: Génération de la couverture de code
        run: pnpm run test:coverage

      - name: Extraction des données de couverture
        id: coverage
        run: |
          # Vérifier si le fichier existe
          if [ -f coverage/coverage-summary.json ]; then
            # Formatter les données pour le commentaire
            STATEMENTS=$(grep -A 1 "Statements" coverage/coverage-summary.json | grep "pct" | awk -F': ' '{print $2}' | sed 's/,//')
            BRANCHES=$(grep -A 1 "Branches" coverage/coverage-summary.json | grep "pct" | awk -F': ' '{print $2}' | sed 's/,//')
            FUNCTIONS=$(grep -A 1 "Functions" coverage/coverage-summary.json | grep "pct" | awk -F': ' '{print $2}' | sed 's/,//')
            LINES=$(grep -A 1 "Lines" coverage/coverage-summary.json | grep "pct" | awk -F': ' '{print $2}' | sed 's/,//')
            
            # Créer le tableau markdown
            COVERAGE_TABLE="| Métrique | Couverture |\n|----------|------------|\n"
            COVERAGE_TABLE+="| Statements | ${STATEMENTS}% |\n"
            COVERAGE_TABLE+="| Branches | ${BRANCHES}% |\n"
            COVERAGE_TABLE+="| Functions | ${FUNCTIONS}% |\n"
            COVERAGE_TABLE+="| Lines | ${LINES}% |"
          else
            COVERAGE_TABLE="| Métrique | Couverture |\n|----------|------------|\n"
            COVERAGE_TABLE+="| Rapport | Non disponible |"
          fi
          
          # Echappement pour les variables GitHub
          COVERAGE_TABLE="${COVERAGE_TABLE//'%'/'%25'}"
          COVERAGE_TABLE="${COVERAGE_TABLE//$'\n'/'%0A'}"
          COVERAGE_TABLE="${COVERAGE_TABLE//$'\r'/'%0D'}"
          
          echo "coverage-table=$COVERAGE_TABLE" >> $GITHUB_OUTPUT

      - name: Publication du commentaire de couverture
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## 📊 Rapport de couverture de code
            
            ${{ steps.coverage.outputs.coverage-table }}
            
            [Voir le rapport détaillé](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Archivage des rapports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./front/playwright-report/
            ./front/coverage/
          retention-days: 30 