name: Lint & Format Check

on:
  pull_request:
    paths:
      - "front/**"
      - ".github/workflows/lint-format.yml"

jobs:
  lint-format:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        working-directory: front

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('front/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: front
        run: yarn install --frozen-lockfile

      - name: Check formatting
        working-directory: front
        run: yarn format:check

      - name: Check ESLint rules
        working-directory: front
        run: yarn lint
