name: Anchor Tests Main branch

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Anchor Deploy in Docker
    runs-on: ubuntu-latest
    
    container:
      image: pylejeune/solana-dev:beta
      # Ne pas utiliser --user root sauf si absolument nécessaire
      # car cela peut modifier l'environnement attendu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set cluster based on branch
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "ANCHOR_RPC=devnet" >> $GITHUB_ENV
            echo "Using devnet cluster for master branch"
          else
            echo "ANCHOR_RPC=localnet" >> $GITHUB_ENV
            echo "Using localnet cluster for other branches"
          fi
      
      - name: Verify ANCHOR_RPC is set
        run: |
          echo "ANCHOR_RPC value: $ANCHOR_RPC"
          if [ -z "$ANCHOR_RPC" ]; then
            echo "ANCHOR_RPC is not set!"
            exit 1
          fi

      - name: Update Anchor.toml with ANCHOR_RPC value
        run: |
          echo "Updating Anchor.toml with ANCHOR_RPC=$ANCHOR_RPC"
          # Utiliser sed pour remplacer la valeur de cluster dans Anchor.toml
          sed -i "s/cluster = \".*\"/cluster = \"$ANCHOR_RPC\"/" programs/Anchor.toml
          # Afficher le contenu modifié pour vérification
          echo "Updated Anchor.toml content:"
          cat programs/Anchor.toml

      - name: Generate Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase --force --outfile ~/.config/solana/id.json

      # Cache pour la compilation Anchor
      - name: Cache Anchor build
        uses: actions/cache@v3
        with:
          path: |
            programs/target
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-anchor-${{ hashFiles('programs/Cargo.lock', 'programs/Cargo.toml', 'programs/programs/**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-anchor-

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-04-01
          targets: wasm32-unknown-unknown  # si nécessaire
      - run: rustup component add rustfmt

      - name: Build Anchor program
        working-directory: programs
        run: |
          rustc --version &&
          anchor --version &&
          RUSTUP_TOOLCHAIN=nightly-2025-04-01 \
          anchor build