name: Notify Discord on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-discord:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_REVIEWER }}
        with:
          args: |
            {
              "embeds": [{
                "title": "✅ PR Approuvée",
                "description": "Une PR a été approuvée !",
                "color": 5814783,
                "fields": [
                  {
                    "name": "PR",
                    "value": "[#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})",
                    "inline": true
                  },
                  {
                    "name": "Auteur",
                    "value": "${{ github.event.pull_request.user.login }}",
                    "inline": true
                  },
                  {
                    "name": "Approuvé par",
                    "value": "${{ github.event.review.user.login }}",
                    "inline": true
                  }
                ],
                "timestamp": "${{ github.event.review.submitted_at }}"
              }]
            } 